apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminders-backend
  namespace: reminders
  labels:
    app: reminders-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminders-backend
  template:
    metadata:
      labels:
        app: reminders-backend
    spec:
      containers:
        - name: backend
          image: andrejt12/reminders-plus-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: reminders-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: reminders-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: reminders-config
                  key: DB_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reminders-secrets
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reminders-secrets
                  key: DB_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: reminders-backend
  namespace: reminders
spec:
  selector:
    app: reminders-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP