apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reminders

resources:
- namespace.yaml
- config-secrets.yaml
- postgres-deployment.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- ingress.yaml

images:
- name: andrejt12/reminders-plus-backend
  newTag: 81e391a9ec9faa06451fff82ebd495c4d3887248
- name: andrejt12/reminders-plus-frontend
  newTag: 81e391a9ec9faa06451fff82ebd495c4d3887248
