apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reminders

resources:
- namespace.yaml
- config-secrets.yaml
- postgres-deployment.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- ingress.yaml

images:
- name: andrejt12/reminders-plus-backend
  newTag: a50485784e52afab3f0e7dd95157f30be00cbcfc
- name: andrejt12/reminders-plus-frontend
  newTag: a50485784e52afab3f0e7dd95157f30be00cbcfc
